#############################################################################
# Makefile for building: OutReel
# Generated by qmake (2.01a) (Qt 4.8.0) on: Tue Apr 23 22:09:36 2013
# Project:  OutReel.pro
# Template: app
# Command: /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile OutReel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtCore -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include/QtGui -I/opt/QtSDK/Desktop/Qt/4.8.0/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/QtSDK/Desktop/Qt/4.8.0/gcc/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/ffmpegfrontend.cpp \
		src/settings.cpp \
		src/about.cpp moc_ffmpegfrontend.cpp \
		moc_about.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		ffmpegfrontend.o \
		settings.o \
		about.o \
		moc_ffmpegfrontend.o \
		moc_about.o \
		qrc_resources.o
DIST          = /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../.qmake.cache \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/static.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		OutReel.pro
QMAKE_TARGET  = OutReel
DESTDIR       = 
TARGET        = OutReel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_ffmpegfrontend.h ui_ffmpegoutput.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OutReel.pro ../../.qmake.cache /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../.qmake.cache \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/static.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile OutReel.pro
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../.qmake.cache:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/static.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
/opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile OutReel.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/OutReel1.0.0 || $(MKDIR) .tmp/OutReel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OutReel1.0.0/ && $(COPY_FILE) --parents src/ffmpegfrontend.h src/settings.h src/about.h .tmp/OutReel1.0.0/ && $(COPY_FILE) --parents src/resources.qrc .tmp/OutReel1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/ffmpegfrontend.cpp src/settings.cpp src/about.cpp .tmp/OutReel1.0.0/ && $(COPY_FILE) --parents src/ffmpegfrontend.ui src/ffmpegoutput.ui src/about.ui .tmp/OutReel1.0.0/ && $(COPY_FILE) --parents translations/ffmpeg-gui_it.ts translations/ffmpeg-gui_ru.ts translations/ffmpeg-gui_ua.ts translations/ffmpeg-gui_de.ts .tmp/OutReel1.0.0/ && (cd `dirname .tmp/OutReel1.0.0` && $(TAR) OutReel1.0.0.tar OutReel1.0.0 && $(COMPRESS) OutReel1.0.0.tar) && $(MOVE) `dirname .tmp/OutReel1.0.0`/OutReel1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OutReel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ffmpegfrontend.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ffmpegfrontend.cpp moc_about.cpp
moc_ffmpegfrontend.cpp: src/ffmpegfrontend.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) src/ffmpegfrontend.h -o moc_ffmpegfrontend.cpp

moc_about.cpp: src/about.h
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) src/about.h -o moc_about.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: src/resources.qrc \
		src/ffmpeg-gui.conf \
		src/3gp.ffpreset \
		src/mp4.ffpreset \
		src/MD-toMP3.ffpreset \
		src/mp3.ffpreset \
		src/wav.ffpreset \
		src/ogg.ffpreset \
		src/mkv.ffpreset \
		src/flv.ffpreset \
		src/MD-to3GP-176x144.ffpreset \
		src/swf.ffpreset \
		src/mov.ffpreset \
		src/m4v.ffpreset \
		src/MD-IPod-320x180.ffpreset \
		translations/ffmpeg-gui_it.qm \
		translations/ffmpeg-gui_ua.qm \
		translations/ffmpeg-gui_de.qm \
		translations/ffmpeg-gui_ru.qm \
		src/a.png \
		src/outreel.png \
		icons/transparent.png \
		icons/circle.png \
		icons/icon32.png
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name resources src/resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ffmpegfrontend.h ui_ffmpegoutput.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ffmpegfrontend.h ui_ffmpegoutput.h ui_about.h
ui_ffmpegfrontend.h: src/ffmpegfrontend.ui
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic src/ffmpegfrontend.ui -o ui_ffmpegfrontend.h

ui_ffmpegoutput.h: src/ffmpegoutput.ui
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic src/ffmpegoutput.ui -o ui_ffmpegoutput.h

ui_about.h: src/about.ui
	/opt/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic src/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/ffmpegfrontend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

ffmpegfrontend.o: src/ffmpegfrontend.cpp src/about.h \
		src/settings.h \
		src/ffmpegfrontend.h \
		ui_ffmpegfrontend.h \
		ui_ffmpegoutput.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ffmpegfrontend.o src/ffmpegfrontend.cpp

settings.o: src/settings.cpp src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o src/settings.cpp

about.o: src/about.cpp src/about.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o src/about.cpp

moc_ffmpegfrontend.o: moc_ffmpegfrontend.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ffmpegfrontend.o moc_ffmpegfrontend.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

